
site:
  author: nnda
  title: nnda's
  description: My personal website.

  authorProfile:
    status:
      icon: üõå
      text: eepy

    description: |
      <s>(self-proclaimed)</s> game developer, front-end web dev, &amp; digital artist/illustrator.

    pronouns: he/him
    pronunciation: /Ààn√¶n.d…ô/
    languages: ID,&nbsp;EN
    location: ID
    timezone: Asia/Jakarta

  note: |
    This website is licensed under the GNU GPLv3.
    The source code is available in the public repository.

repoURL: github.com/nndda/website

nav:
  links:
    - name: Projects
      url: \#projects

    - name: Illustrations
      url: \#illustrations

    - icon: itchdotio
      url: nnda.itch.io
      external: true

    - icon: artstation
      url: www.artstation.com/nnda
      external: true

    - icon: github
      url: github.com/nndda
      external: true

# -------------------------------------------------------------------------------------------------

stacks:
  - group: Ë™û
    icon: code
    items:
      - TypeScript
      - JavaScript
      - Python
      - Rust

  - group: „Ç¶„Çß„Éñ
    icon: server
    items:
      - Node.js
      - webpack
      - CSS
      - SCSS
      - Cloudflare
      # - Cloudflare Pages
      # - Cloudflare Workers

  - group: „ÉÑ„Éº„É´
    icon: toolbox
    items:
      - Linux
      - Git
      - GitHub Actions

  - group: „Ç§„É©„Çπ„Éà
    icon: paintbrush
    items:
      - Medibang Paint
      - Inkscape

  - group: „Ç≤„Éº„É†
    icon: gamepad
    items:
      - GDScript
      - Aseprite

# -------------------------------------------------------------------------------------------------

socials:
  - group: My Main Works
    links:
      - name: GitHub
        url: github.com/nndda
        icon: github
        redirect: /github
        username: nndda

      - name: itch.io
        url: nnda.itch.io
        icon: itchdotio
        redirect: /itchio
        username: nnda

      - name: Patreon
        url: patreon.com/nnda
        icon: patreon
        redirect: /patreon
        username: nnda

  - group: Artworks & Illustrations
    links:
      - name: ArtStation
        url: artstation.com/nnda
        icon: artstation
        redirect: /artstation
        username: nnda

      - name: cara.app
        url: cara.app/nnda
        redirect: /cara
        username: nnda

  - group: Socials
    links:
      - name: Mastodon
        url: mastodon.art/@nnda
        icon: mastodon
        redirect: /mastodon
        username: '@nnda'

      - name: Twitter/X
        url: twitter.com/@nnda_dev
        icon: x
        redirect: /twitter
        username: '@nnda_dev'

      - name: Bluesky
        url: bsky.app/profile/nnda.dev
        icon: bluesky
        redirect: /bsky
        username: '@nnda.dev'

# -------------------------------------------------------------------------------------------------

projects:
  - name: Theatre
    url: https://github.com/nndda/Theatre
    tags: [ Godot, GDScript ]
    category: Game Development
    platform: N/A
    description: |
      üé≠ Yet another (linear) dialogue system/addon/plugin for Godot. Written in human-readable plain text. Compatible with Godot 4.3.

    image: /assets/project-theatre.avif

  - name: Pitch
    url: https://nnda.itch.io/pitch
    tags: [ Web, TypeScript, SCSS ]
    category: Web Project
    platform: Web
    description: |
      üß© Collection of UI components and tweaks, designed specifically for itch.io project pages.

    image: /assets/project-pitch.avif

  - name: Obscura
    url: https://nnda.itch.io/obscura
    tags: [ Web, Rust, TypeScript ]
    category: Web Project
    platform: Web
    description: |
      üò∂‚Äçüå´Ô∏è Image obfuscation library for the web. 

  - name: This website
    url: https://github.com/nndda/website
    tags: [ Web, TypeScript, SCSS ]
    category: Web Project
    platform: Web
    description: |
      üå∏ My personal static site and an all-in-one hub for my social presence. (Almost) vanilla, framework-free, modular, & backend-less.

  - name: itchio-profile
    url: https://github.com/nndda/itchio-profile
    tags: [ Node, JavaScript, SCSS ]
    category: Web Project
    platform: Web
    description: |
      Source code for my itch.io profile page.

# -------------------------------------------------------------------------------------------------

illustrations:

  # - title: Illustration's Title
  #   chr: [ Character/Subject ]
  #   src: /assets/illust-file.webp
