name: Check dependency licenses

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'package.json'
      - 'config/.licensed.yml'
      - '.github/workflows/licensed.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'package.json'
      - 'config/.licensed.yml'
      - '.github/workflows/licensed.yml'
  workflow_dispatch:

jobs:
  licensed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Cache Ruby gems
        id: gem-cache
        uses: actions/cache@v5
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-licensed

      - name: Install licensed gem
        if: steps.gem-cache.outputs.cache-hit != 'true'
        run: gem install licensed --install-dir vendor/bundle

      - name: Add gems to GEM_PATH
        run: echo "GEM_PATH=$GEM_PATH:$(pwd)/vendor/bundle" >> $GITHUB_ENV

      - name: Install project dependencies
        run: npm ci --omit=dev

      - name: Check licenses
        run: |
          ./vendor/bundle/bin/licensed cache --config=./config/.licensed.yml && \
          ./vendor/bundle/bin/licensed status --config=./config/.licensed.yml
