name: ESLint

on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**/*.ts'
      - '**/*.js'
      - '.github/workflows/lint-scripts.yml'
      - 'config/eslint.config.mjs'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.ts'
      - '**/*.js'
      - '.github/workflows/lint-scripts.yml'
      - 'config/eslint.config.mjs'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Cache linting dependencies
        id: eslint-cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-npm-eslint

      - name: Install linting dependencies
        run: |
          npm install --no-save \
            jiti \
            @eslint/js \
            @eslint/compat \
            eslint \
            globals \
            typescript-eslint

      - name: Lint scripts
        run: npm run lint:scripts